arch:
  - arm64

jobs:
  include:
    - stage: build
      script:
        - echo "Running on AWS Graviton2 architecture"
        - ls -la # List files in the current directory for debugging
        - chmod +x ./build-script.sh # Ensure the script is executable
        - ./build-script.sh
